coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 70%
        threshold: 5%

parsers:
  go:
    partials_as_hits: false

comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
